### ISSUE TITLE
Support esp32 ble

### ISSUE THREAD

**Issue by riker65** [cyrils/renogy-bt#71] opened 2024-06-26 18:32 UTC
Hi
Using the great program to monitor the renogy charger.

Is there an option to support also esp32 ble?

I was not able to change the code.

Thanks for hints

**Comment by cyrils** [comment] 2024-06-28 04:48
Hello, this is written in cpython, porting it to esp32 requires rewriting on micropython. Its totally doable, but requires some effort. There are plenty of examples for connecting to BLE peripheral from esp32/pico w. Might be future work.

**Comment by cyrils** [comment] 2024-06-28 04:53
Marking as duplicate of https://github.com/cyrils/renogy-bt/issues/49

**Closed by cyrils** 2024-06-28 04:53 UTC
Labels: duplicate, enhancement
